version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    volumes:
       - sqlite_database:/db
    ports:
      - "5001:5001"
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "5000:5000"
    environment:
      - DATABASE=/db/minitwit.db
    restart: always
volumes:
  sqlite_database:
