version: "3"
services:
  postgres:
    image: postgres:15-alpine
    container_name: minitwit-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: minitwit
      POSTGRES_PASSWORD: password
      POSTGRES_DB: minitwit
    ports:
      - "5432:5432"
    networks:
      - minitwit-net

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    volumes:
      - sqlite_database:/db
    ports:
      - "5001:5001"
    restart: always
    # volumes:
    #   - ./db/minitwit.db:/db/minitwit.db
    # ports:
    #   - "5001:5001"
    # environment:
    #   - DATABASE=/db/minitwit.db
    # restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "5000:5000"
    environment:
      - DATABASE=/db/minitwit.db
    restart: always
volumes:
  sqlite_database:
