version: "3"
services:
  postgres:
    image: postgres:15-alpine
    container_name: minitwit-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: minitwit
      POSTGRES_PASSWORD: password
      POSTGRES_DB: minitwit
    ports:
      - "5432:5432"
    networks:
      - minitwit-net

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: minitwit
      DB_PASSWORD: password
      DB_NAME: minitwit
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    networks:
      - minitwit-net
    restart: always
    # volumes:
    #   - ./db/minitwit.db:/db/minitwit.db
    # ports:
    #   - "5001:5001"
    # environment:
    #   - DATABASE=/db/minitwit.db
    # restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    volumes:
      - ./db/minitwit.db:/db/minitwit.db
    ports:
      - "5000:5000"
    environment:
      - DATABASE=/db/minitwit.db
    restart: always

networks:
  minitwit-net:


volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /path/to/backups/postgres_data
