version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    volumes:
       - sqlite_database:/db
       - api_logs:/logs   
    ports:
      - "5001:5001"
    restart: always

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "5000:5000"
    environment:
      - DATABASE=/db/minitwit.db
    restart: always

  promtail:
    build:
      context: .
      dockerfile: Dockerfile-logging
    volumes:
      - api_logs:/logs               
      - ./logging/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /tmp:/tmp
    depends_on:
      - api
    restart: always

volumes:
  sqlite_database:
  api_logs:

