events {}

http {
    upstream api_backend {
        server api:5001; # Switch to api_new
    }

    server {
        listen 5001;

        location / {
            proxy_pass http://api_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
