scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-uptime'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - "209.38.115.34:5001"  # No http://
          - "209.38.115.34:5000"  # No http://
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'http-traffic'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - "209.38.115.34:5001"  # No http://
          - "209.38.115.34:5000"  # No http://
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
