global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

  # Attach these extra labels to all timeseries collected by this Prometheus instance.
  external_labels:
    monitor: "codelab-monitor"

rule_files:
  - "prometheus.rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:5001"]

  - job_name: "api-uptime"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - "209.38.115.34:5002" # No http://
          - "209.38.115.34:5000" # No http://
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: "http-traffic"
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - "209.38.115.34:5002" # No http://
          - "209.38.115.34:5000" # No http://
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
