server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://209.38.43.0:3100/loki/api/v1/push

scrape_configs:
  - job_name: go-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: go-app
          host: your-local-machine
          __path__: /var/log/myapp/*.log
