version: "3.8"
services:
  api:
    image: alialexandra/api:latest
    environment:
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASSWORD
      - DB_NAME
      - AUTH_HEADER
    volumes:
      - sqlite_database:/db
      - api_logs:/logs
    ports:
      - "5001:5001"
    deploy:
      mode: replicated
      replicas: 1
    restart: always

  web:
    image: alialexandra/web:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE=/db/minitwit.db
    deploy:
      mode: replicated
      replicas: 1
    restart: always

  promtail:
    image: alialexandra/promtail:latest
    volumes:
      - api_logs:/logs
      - /tmp:/tmp
    configs:
      - source: promtail_config
        target: /etc/promtail/promtail-config.yaml
    deploy:
      mode: global  # One instance per node
    restart: always

volumes:
  sqlite_database:
    driver: local
  api_logs:
    driver: local

configs:
  promtail_config:
    file: ./logging/promtail-config.yaml