---
    name: Continuous Deployment
    
    on:
      push:
        # Run workflow every time something is pushed to the main branch
        branches:
          - main
          #- deployment
      # allow manual triggers for now too
      workflow_dispatch:
        manual: true
    
    # Remember to set the following secrets in your repository's settings:
    # https://github.com/your_username/itu-minitwit-ci/settings/secrets/actions
    # DOCKER_USERNAME
    # DOCKER_PASSWORD
    # SSH_USER
    # SSH_KEY
    # SSH_HOST
    
    jobs:
      build:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout
            uses: actions/checkout@v2
    
          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
    
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
    
          - name: Build and push web
            uses: docker/build-push-action@v6
            with:
              context: .
              file: ./Dockerfile-web
              push: true
              tags: ${{ secrets.DOCKER_USERNAME }}/web:latest
              cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/web:webbuildcache
              cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/web:webbuildcache,mode=max

          - name: Build and push api
            uses: docker/build-push-action@v6
            with:
              context: .
              file: ./Dockerfile-api
              push: true
              tags: ${{ secrets.DOCKER_USERNAME }}/api:latest
              cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/api:webbuildcache
              cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/api:webbuildcache,mode=max
    
          #- name: Test minitwit
          #  run: |
          #    docker build -t $DOCKER_USERNAME/minitwittestimage -f Dockerfile-go-api-test .
          #    yes 2>/dev/null | docker compose up -d
          #    docker run --rm $DOCKER_USERNAME/minitwittestimage
          #  env:
          #    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    
          #- name: Configure SSH
          #  run: |
          #    mkdir -p ~/.ssh/
          #    echo "$SSH_KEY" > ~/.ssh/id_ed25519
          #    chmod 600 ~/.ssh/id_ed25519
          #  env:
          #    SSH_KEY: ${{ secrets.SSH_KEY }}
          
          #- name: Deploy to server
          #  # Configure the ~./bash_profile and deploy.sh file on the Vagrantfile
          #  run: >
          #    ssh $SSH_USER@$SSH_HOST
          #    -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no
          #    '/minitwit/deploy.sh'
          #  env:
          #    SSH_USER: ${{ secrets.SSH_USER }}
          #    SSH_HOST: ${{ secrets.SSH_HOST }}